### Creating the following model

![Layered Architecture](Layered_Architecture.png)

In [3]:
import numpy as np

In [4]:
input_size = 3 # no of input features
layers = [3,2] # no of neurons in 1st and 2nd hidden layer
output_size = 2 # no of neurons in output layer

In [5]:
class NeuralNetwork:
    def _init__(self,input_size,layers,output_size):
        np.random.seed(0)
        
        model = {} # Dictionary
        # Defining weights
        # Weight Matrix : Random matrix of size 3*3
        model['w1'] = np.random.randn(input_size,layers[0])
        # Bias Term : Contain the bias for all 3 neurons
        model['b1'] = np.zeros(1,layers[0])
        
        # Random weight matrix of sixe 3*2
        model['w2'] = np.random.randn(layers[0],layers[1])
        model['b2'] = np.zeros(1,layers[1])
    
        # Random weight matrix of size 2*2
        model['w3'] = np.random.randn(layers[1],output_size)
        model['b3'] = np.zeros(1,output_size)
        
        self.model = model

In [6]:
w1 = np.random.randn(input_size,layers[0])
print(w1)

[[ 0.37974374  0.35671221 -0.49994357]
 [-0.96762615  1.71442259  0.29481265]
 [-1.02779057  0.82662994  0.31123093]]
